variables:
    GIT_STRATEGY: clone

stages:
  - test
    
before_script:

gcc_w/o_OpenBLAS:
  stage: test
  image: d6ac9435774b
  script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - PATH=${PATH}:/opt/FJSVstclanga/v1.0.0/bin:/opt/cmake/3_17_3/bin/
#  - export LD_LIBRARY_PATH=/opt/FJSVstclanga/v1.0.0/lib64:/usr/lib64/libcblas.so
  - export LD_LIBRARY_PATH=/usr/lib64/libopenblas-r0.3.3.so
#   - export LD_LIBRARY_PATH=/opt/FJSVstclanga/v1.0.0/lib64:/usr/lib64/libopenblas-r0.3.3.so
#  - export CC="fcc -Nclang -Knolargepage"
#  - export CXX="FCC -Nclang -Knolargepage" 
  - mkdir third_party/build_xed_aarch64
  - pushd third_party/build_xed_aarch64/
  - ../xbyak_translator_aarch64/translator/third_party/xed/mfile.py --shared examples install
  - cd kits/
  - ln -sf xed-install-base-* xed
  - popd
  - mkdir build_aarch64
  - cd build_aarch64/
  - yum install which -y
  - which -a cmake
  - echo $PATH  
  - cmake .. 
  - make -j48
  - cd tests/gtests
  - ctest
  - ctest -R test_concat
  - cd ../benchdnn
  - ./benchdnn --conv --batch=inputs/conv_resnet_50
  - ./benchdnn --bnorm --batch=inputs/bnorm/bnorm_resnet_50
#  tags:
#    - instruction_unit
#

gcc_w/_OpenBLAS:
  stage: test
  image: d6ac9435774b
  script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
#  - PATH=${PATH}:/opt/FJSVstclanga/v1.0.0/bin
#  - export LD_LIBRARY_PATH=/opt/FJSVstclanga/v1.0.0/lib64:/usr/lib64/libcblas.so
  - export LD_LIBRARY_PATH=/usr/lib64/libopenblas-r0.3.3.so
#   - export LD_LIBRARY_PATH=/opt/FJSVstclanga/v1.0.0/lib64:/usr/lib64/libopenblas-r0.3.3.so
#  - export CC="fcc -Nclang -Knolargepage"
#  - export CXX="FCC -Nclang -Knolargepage" 
  - mkdir third_party/build_xed_aarch64
  - pushd third_party/build_xed_aarch64/
  - ../xbyak_translator_aarch64/translator/third_party/xed/mfile.py --shared examples install
  - cd kits/
  - ln -sf xed-install-base-* xed
  - popd
  - mkdir build_aarch64
  - cd build_aarch64/
  - cmake .. -DWITH_BLAS=openblas
  - make -j48
  - cd tests/gtests
  - ctest
#  - ctest -R test_concat
  - cd ../benchdnn
  - ./benchdnn --conv --batch=inputs/conv_resnet_50
  - ./benchdnn --bnorm --batch=inputs/bnorm/bnorm_resnet_50
#  tags:
#    - instruction_unit

fcc_w/o_SSL2:
  stage: test
  image: d6ac9435774b
  script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - PATH=${PATH}:/opt/FJSVstclanga/v1.0.0/bin
  - export LD_LIBRARY_PATH=/opt/FJSVstclanga/v1.0.0/lib64:/usr/lib64/libcblas.so
#  - export LD_LIBRARY_PATH=/usr/lib64/libcblas.so
#   - export LD_LIBRARY_PATH=/opt/FJSVstclanga/v1.0.0/lib64:/usr/lib64/libopenblas-r0.3.3.so
  - export CC="fcc -Nclang -Knolargepage"
  - export CXX="FCC -Nclang -Knolargepage" 
  - mkdir third_party/build_xed_aarch64
  - pushd third_party/build_xed_aarch64/
  - ../xbyak_translator_aarch64/translator/third_party/xed/mfile.py --shared examples install
  - cd kits/
  - ln -sf xed-install-base-* xed
  - popd
  - mkdir build_aarch64
  - cd build_aarch64/
  - cmake ..
  - make -j48
  - cd tests/gtests
  - ctest
#  - ctest -R test_concat
  - cd ../benchdnn
  - ./benchdnn --conv --batch=inputs/conv_resnet_50
  - ./benchdnn --bnorm --batch=inputs/bnorm/bnorm_resnet_50
#  tags:
#    - instruction_unit

fcc_w/_SSL2:
  stage: test
  image: d6ac9435774b
  script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - PATH=${PATH}:/opt/FJSVstclanga/v1.0.0/bin
  - export LD_LIBRARY_PATH=/opt/FJSVstclanga/v1.0.0/lib64:/usr/lib64/libcblas.so
#  - export LD_LIBRARY_PATH=/usr/lib64/libcblas.so
#   - export LD_LIBRARY_PATH=/opt/FJSVstclanga/v1.0.0/lib64:/usr/lib64/libopenblas-r0.3.3.so
  - export CC="fcc -Nclang -Knolargepage"
  - export CXX="FCC -Nclang -Knolargepage" 
  - mkdir third_party/build_xed_aarch64
  - pushd third_party/build_xed_aarch64/
  - ../xbyak_translator_aarch64/translator/third_party/xed/mfile.py --shared examples install
  - cd kits/
  - ln -sf xed-install-base-* xed
  - popd
  - mkdir build_aarch64
  - cd build_aarch64/
  - cmake .. -DWITH_BLAS=ssl2
  - make -j48
  - cd tests/gtests
  - ctest
#  - ctest -R test_concat
  - cd ../benchdnn
  - ./benchdnn --conv --batch=inputs/conv_resnet_50
  - ./benchdnn --bnorm --batch=inputs/bnorm/bnorm_resnet_50
#  tags:
#    - instruction_unit

